{
  config,
  lib,
  pkgs,
  ...
}@inputs:

with inputs; {
  environment.systemPackages = with pkgs; [
    libtool
    gcc
    gnumake
    cmake
    kotlin-language-server
    kotlin
    ktlint
    rust-analyzer
    rustc
    cargo
    rustfmt
    clippy
    jetbrains.idea-community
    nil
    nixfmt-rfc-style
    nixpkgs-fmt
    vscodium
    jdk21
    graphviz
    shfmt
    shellcheck
    ripgrep
    wordnet
    ghc
    haskell-language-server
    cabal-install
    unstable.go
    unstable.gopls
    unstable.golangci-lint-langserver
    unstable.golangci-lint
    impl
    gotests
    nodePackages_latest.vscode-html-languageserver-bin
    nodePackages_latest.vscode-css-languageserver-bin
    delve
    httpie
    lldb_16
    zigpkgs.master
    unstable.zls
  ];
  programs.java.enable = true;
}
